### PR TITLE
added bigger icons

### PR DESCRIPTION
**Pull request by cheeseer**
added bigger icons

### CODE REVIEW

**Comment by cygaar** [comment]
Do we really need this?

**Comment by cheeseer** [comment]
It's not needed. It's mainly to enlarge the favicon so it's easier to distinguish your twitter tabs if you have a lot of tabs open.

**Comment by TheBrockReal** [comment]
Fuck PC, do it for mobile

**Comment by raid5** [comment]
This seems like a good update to me, the icons are a bit smaller than my other icons.

Screenshot 2023-07-28 at 10 01 34 AM

**Comment by cygaar** [comment]
Taking a look

**Review by cygaar — APPROVED** [review]

**Pull request merged**
